// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// didgpu_cpp_core_one_event_time
List didgpu_cpp_core_one_event_time(NumericVector outcome, NumericVector N_gt, IntegerVector group_id, IntegerVector time_id, IntegerVector cohort_id, IntegerVector F_g, IntegerVector S_g, IntegerVector T_g, IntegerVector L_g, IntegerVector group_offset, int n_cohorts, int k, int direction);
RcppExport SEXP _didgpu_didgpu_cpp_core_one_event_time(SEXP outcomeSEXP, SEXP N_gtSEXP, SEXP group_idSEXP, SEXP time_idSEXP, SEXP cohort_idSEXP, SEXP F_gSEXP, SEXP S_gSEXP, SEXP T_gSEXP, SEXP L_gSEXP, SEXP group_offsetSEXP, SEXP n_cohortsSEXP, SEXP kSEXP, SEXP directionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_id(group_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_id(time_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cohort_id(cohort_idSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type F_g(F_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type S_g(S_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type T_g(T_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L_g(L_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_offset(group_offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_cohorts(n_cohortsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type direction(directionSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cpp_core_one_event_time(outcome, N_gt, group_id, time_id, cohort_id, F_g, S_g, T_g, L_g, group_offset, n_cohorts, k, direction));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cpu_hello
double didgpu_cpu_hello();
RcppExport SEXP _didgpu_didgpu_cpu_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(didgpu_cpu_hello());
    return rcpp_result_gen;
END_RCPP
}
// didgpu_has_cuda_support
bool didgpu_has_cuda_support();
RcppExport SEXP _didgpu_didgpu_has_cuda_support() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(didgpu_has_cuda_support());
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_did
double didgpu_cuda_did(Rcpp::NumericVector outcome, Rcpp::NumericVector N_gt, Rcpp::IntegerVector row_to_g, Rcpp::IntegerVector row_to_t, Rcpp::IntegerVector cohort_key, Rcpp::IntegerVector F_g, Rcpp::IntegerVector S_g, Rcpp::IntegerVector T_g, Rcpp::IntegerVector L_g, int n_cohorts, int k, int direction, double G_over_Ninc);
RcppExport SEXP _didgpu_didgpu_cuda_did(SEXP outcomeSEXP, SEXP N_gtSEXP, SEXP row_to_gSEXP, SEXP row_to_tSEXP, SEXP cohort_keySEXP, SEXP F_gSEXP, SEXP S_gSEXP, SEXP T_gSEXP, SEXP L_gSEXP, SEXP n_cohortsSEXP, SEXP kSEXP, SEXP directionSEXP, SEXP G_over_NincSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type row_to_g(row_to_gSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type row_to_t(row_to_tSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cohort_key(cohort_keySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type F_g(F_gSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type S_g(S_gSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type T_g(T_gSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type L_g(L_gSEXP);
    Rcpp::traits::input_parameter< int >::type n_cohorts(n_cohortsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type direction(directionSEXP);
    Rcpp::traits::input_parameter< double >::type G_over_Ninc(G_over_NincSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_did(outcome, N_gt, row_to_g, row_to_t, cohort_key, F_g, S_g, T_g, L_g, n_cohorts, k, direction, G_over_Ninc));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_fect_fe_r
Rcpp::List didgpu_cuda_fect_fe_r(Rcpp::NumericMatrix Y, Rcpp::IntegerMatrix M, double tol, int max_iter);
RcppExport SEXP _didgpu_didgpu_cuda_fect_fe_r(SEXP YSEXP, SEXP MSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_fect_fe_r(Y, M, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_run_saxpy
Rcpp::NumericVector didgpu_run_saxpy(double a, Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _didgpu_didgpu_run_saxpy(SEXP aSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_run_saxpy(a, x, y));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_multiplier_bootstrap_r
SEXP didgpu_cuda_multiplier_bootstrap_r(Rcpp::NumericMatrix IF, int B, int mult_kind, int seed);
RcppExport SEXP _didgpu_didgpu_cuda_multiplier_bootstrap_r(SEXP IFSEXP, SEXP BSEXP, SEXP mult_kindSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type IF(IFSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type mult_kind(mult_kindSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_multiplier_bootstrap_r(IF, B, mult_kind, seed));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_cluster_bootstrap_r
SEXP didgpu_cuda_cluster_bootstrap_r(Rcpp::NumericMatrix IF, Rcpp::IntegerVector cluster_id, int n_clusters, int B, int seed);
RcppExport SEXP _didgpu_didgpu_cuda_cluster_bootstrap_r(SEXP IFSEXP, SEXP cluster_idSEXP, SEXP n_clustersSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type IF(IFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type cluster_id(cluster_idSEXP);
    Rcpp::traits::input_parameter< int >::type n_clusters(n_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_cluster_bootstrap_r(IF, cluster_id, n_clusters, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_testmechs_bootstrap_r
SEXP didgpu_cuda_testmechs_bootstrap_r(Rcpp::IntegerVector d, Rcpp::IntegerVector m, Rcpp::IntegerVector y, int B, int K, int dy, int seed);
RcppExport SEXP _didgpu_didgpu_cuda_testmechs_bootstrap_r(SEXP dSEXP, SEXP mSEXP, SEXP ySEXP, SEXP BSEXP, SEXP KSEXP, SEXP dySEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type dy(dySEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_testmechs_bootstrap_r(d, m, y, B, K, dy, seed));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_fect_svd_truncated_r
SEXP didgpu_cuda_fect_svd_truncated_r(Rcpp::NumericMatrix M, int r);
RcppExport SEXP _didgpu_didgpu_cuda_fect_svd_truncated_r(SEXP MSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_fect_svd_truncated_r(M, r));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_fect_svd_softthreshold_r
SEXP didgpu_cuda_fect_svd_softthreshold_r(Rcpp::NumericMatrix Y_complete, double lambda);
RcppExport SEXP _didgpu_didgpu_cuda_fect_svd_softthreshold_r(SEXP Y_completeSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y_complete(Y_completeSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_fect_svd_softthreshold_r(Y_complete, lambda));
    return rcpp_result_gen;
END_RCPP
}
// didgpu_cuda_cs_inner_batched_r
SEXP didgpu_cuda_cs_inner_batched_r(Rcpp::NumericVector X_concat, Rcpp::IntegerVector X_offsets, Rcpp::NumericVector Y_concat, Rcpp::NumericVector W_concat, Rcpp::IntegerVector unit_id_per_row, int p, int n_units, int est_method, bool want_influence);
RcppExport SEXP _didgpu_didgpu_cuda_cs_inner_batched_r(SEXP X_concatSEXP, SEXP X_offsetsSEXP, SEXP Y_concatSEXP, SEXP W_concatSEXP, SEXP unit_id_per_rowSEXP, SEXP pSEXP, SEXP n_unitsSEXP, SEXP est_methodSEXP, SEXP want_influenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X_concat(X_concatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type X_offsets(X_offsetsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Y_concat(Y_concatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type W_concat(W_concatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type unit_id_per_row(unit_id_per_rowSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type est_method(est_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type want_influence(want_influenceSEXP);
    rcpp_result_gen = Rcpp::wrap(didgpu_cuda_cs_inner_batched_r(X_concat, X_offsets, Y_concat, W_concat, unit_id_per_row, p, n_units, est_method, want_influence));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_didgpu_didgpu_cpp_core_one_event_time", (DL_FUNC) &_didgpu_didgpu_cpp_core_one_event_time, 13},
    {"_didgpu_didgpu_cpu_hello", (DL_FUNC) &_didgpu_didgpu_cpu_hello, 0},
    {"_didgpu_didgpu_has_cuda_support", (DL_FUNC) &_didgpu_didgpu_has_cuda_support, 0},
    {"_didgpu_didgpu_cuda_did", (DL_FUNC) &_didgpu_didgpu_cuda_did, 13},
    {"_didgpu_didgpu_cuda_fect_fe_r", (DL_FUNC) &_didgpu_didgpu_cuda_fect_fe_r, 4},
    {"_didgpu_didgpu_run_saxpy", (DL_FUNC) &_didgpu_didgpu_run_saxpy, 3},
    {"_didgpu_didgpu_cuda_multiplier_bootstrap_r", (DL_FUNC) &_didgpu_didgpu_cuda_multiplier_bootstrap_r, 4},
    {"_didgpu_didgpu_cuda_cluster_bootstrap_r", (DL_FUNC) &_didgpu_didgpu_cuda_cluster_bootstrap_r, 5},
    {"_didgpu_didgpu_cuda_testmechs_bootstrap_r", (DL_FUNC) &_didgpu_didgpu_cuda_testmechs_bootstrap_r, 7},
    {"_didgpu_didgpu_cuda_fect_svd_truncated_r", (DL_FUNC) &_didgpu_didgpu_cuda_fect_svd_truncated_r, 2},
    {"_didgpu_didgpu_cuda_fect_svd_softthreshold_r", (DL_FUNC) &_didgpu_didgpu_cuda_fect_svd_softthreshold_r, 2},
    {"_didgpu_didgpu_cuda_cs_inner_batched_r", (DL_FUNC) &_didgpu_didgpu_cuda_cs_inner_batched_r, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_didgpu(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
