# R-level wrappers for the Rcpp-exported native routines. These exist
# so roxygen can pick up @export tags; the actual definitions live in
# R/RcppExports.R (auto-generated by Rcpp::compileAttributes()).

#' Report whether didgpu was compiled with CUDA support
#'
#' Returns `TRUE` if the package was built with the NVIDIA CUDA Toolkit
#' available (so `src/cuda_*.cu` was compiled and linked into the
#' package DLL), `FALSE` otherwise. See [didgpu_backend_info()] for the
#' user-facing way to inspect backend availability.
#'
#' @return Logical.
#' @export
#' @name didgpu_has_cuda_support
NULL

#' Run a SAXPY (y = a*x + y) on the GPU
#'
#' Smoke-test for the CUDA toolchain. Computes y = a*x + y on the GPU
#' and returns the result. Only available when the package was built
#' with CUDA support; otherwise errors.
#'
#' @param a Numeric scalar.
#' @param x,y Numeric vectors of the same length.
#' @return Updated `y` vector.
#' @export
#' @name didgpu_run_saxpy
NULL

#' Smoke target for the CPU build path
#'
#' Returns a fixed value (42). Used to verify the CPU half of the build
#' system works in isolation from any GPU machinery.
#'
#' @return Numeric scalar.
#' @export
#' @name didgpu_cpu_hello
NULL
