# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

didgpu_cpp_core_one_event_time <- function(outcome, N_gt, group_id, time_id, cohort_id, F_g, S_g, T_g, L_g, group_offset, n_cohorts, k, direction) {
    .Call(`_didgpu_didgpu_cpp_core_one_event_time`, outcome, N_gt, group_id, time_id, cohort_id, F_g, S_g, T_g, L_g, group_offset, n_cohorts, k, direction)
}

didgpu_cpu_hello <- function() {
    .Call(`_didgpu_didgpu_cpu_hello`)
}

didgpu_has_cuda_support <- function() {
    .Call(`_didgpu_didgpu_has_cuda_support`)
}

didgpu_cuda_did <- function(outcome, N_gt, row_to_g, row_to_t, cohort_key, F_g, S_g, T_g, L_g, n_cohorts, k, direction, G_over_Ninc) {
    .Call(`_didgpu_didgpu_cuda_did`, outcome, N_gt, row_to_g, row_to_t, cohort_key, F_g, S_g, T_g, L_g, n_cohorts, k, direction, G_over_Ninc)
}

didgpu_cuda_fect_fe_r <- function(Y, M, tol, max_iter) {
    .Call(`_didgpu_didgpu_cuda_fect_fe_r`, Y, M, tol, max_iter)
}

didgpu_run_saxpy <- function(a, x, y) {
    .Call(`_didgpu_didgpu_run_saxpy`, a, x, y)
}

didgpu_cuda_multiplier_bootstrap_r <- function(IF, B, mult_kind, seed) {
    .Call(`_didgpu_didgpu_cuda_multiplier_bootstrap_r`, IF, B, mult_kind, seed)
}

didgpu_cuda_cluster_bootstrap_r <- function(IF, cluster_id, n_clusters, B, seed) {
    .Call(`_didgpu_didgpu_cuda_cluster_bootstrap_r`, IF, cluster_id, n_clusters, B, seed)
}

didgpu_cuda_testmechs_bootstrap_r <- function(d, m, y, B, K, dy, seed) {
    .Call(`_didgpu_didgpu_cuda_testmechs_bootstrap_r`, d, m, y, B, K, dy, seed)
}

didgpu_cuda_fect_svd_truncated_r <- function(M, r) {
    .Call(`_didgpu_didgpu_cuda_fect_svd_truncated_r`, M, r)
}

didgpu_cuda_fect_svd_softthreshold_r <- function(Y_complete, lambda) {
    .Call(`_didgpu_didgpu_cuda_fect_svd_softthreshold_r`, Y_complete, lambda)
}

didgpu_cuda_cs_inner_batched_r <- function(X_concat, X_offsets, Y_concat, W_concat, p, n_units, est_method, want_influence) {
    .Call(`_didgpu_didgpu_cuda_cs_inner_batched_r`, X_concat, X_offsets, Y_concat, W_concat, p, n_units, est_method, want_influence)
}

